name: marvel_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  beamer: ^1.5.3
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.19
  gap: ^2.0.1
  google_fonts: ^4.0.3
  http: ^0.13.5
  intl: ^0.18.0
  path_provider: ^2.0.14
  very_good_analysis: ^4.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#000000"
  image: "assets/splash.png"

  android_12:
    color: "#000000"
    image: "assets/splash.png"

flutter_icons:
  image_path: "assets/launcher_icon.png"
  adaptive_icon_background: "assets/launcher_bg.png"
  adaptive_icon_foreground: "assets/launcher_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true